// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"bakery/cloud/producer/docker"
	"bakery/cloud/producer/http"
	"bakery/cloud/producer/http/containers"
	"github.com/gorilla/mux"
)

// Injectors from application.go:

func Init(httpServerConfig2 http.HTTPServerConfig) (*Application, error) {
	router := mux.NewRouter()
	client := docker.NewClient()
	containersController := containers.NewContainersController(client)
	v := composeHTTPControllers(containersController)
	httpServer := &http.HTTPServer{
		Config:      httpServerConfig2,
		Router:      router,
		Controllers: v,
	}
	application := &Application{
		HTTPServer: httpServer,
	}
	return application, nil
}

// application.go:

type Application struct {
	HTTPServer *http.HTTPServer
}

func composeHTTPControllers(
	containersController *containers.ContainersController,
) *[]http.HTTPController {
	return &[]http.HTTPController{
		containersController,
	}
}
